### ISSUE TITLE
Использование https

### ISSUE THREAD

**Issue by Plyha** [TheMurmabis/StatusOpenVPN#10]
Добрый день, подскажите возможно ли настроить https? Я так понимаю в момент аутентификации на web пароль передаётся в явном виде и есть возможность перехватить его, хотелось бы этого избежать.

Спасибо

**Comment by TheMurmabis** [comment]
Здравствуйте! Настройка https на данном этапе не планируется. 
А так в форме входа реализована [CSRF-защита](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B6%D1%81%D0%B0%D0%B9%D1%82%D0%BE%D0%B2%D0%B0%D1%8F_%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D0%BB%D0%BA%D0%B0_%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%B0). 

Работает следующим образом:

+ CSRF-токен генерируется и добавляется в форму при рендеринге шаблона входа.
+ При отправке формы, Flask-WTF проверяет, соответствует ли отправленный токен тому, который был сгенерирован для текущего сеанса пользователя.
+ Если токен не совпадает или отсутствует, запрос отклоняется, и происходит ошибка CSRF.
