### ISSUE TITLE
Автозаполнение на мобильных устройствах

### ISSUE THREAD

**Issue by TripleA150** [TheMurmabis/StatusOpenVPN#11]
Большое спасибо за такой удобный интерфейс. Есть возможность сделать, чтобы iOS устройства распознавали поле с паролем для работы автозаполнения?

**Comment by TheMurmabis** [comment]
Здравствуйте. Спасибо за отзыв)) Добавил атрибут автозаполнения, возможно это поможет решить проблему. 
К сожалению, нет возможности проверить на iOS устройствах. Протестировано на Google Chrome и Яндекс Браузере, все работает.

**Comment by TheMurmabis** [comment]
Да, это из-за http. Если сохранить принудительно то должно сработать.
