### ISSUE TITLE
Неправильно считается скорость клиента

### ISSUE THREAD

**Issue by Plyha** [TheMurmabis/StatusOpenVPN#14]
Добрый вечер, обновился до последней версии и теперь вижу, что можно смотреть реальный ip и скорость клиента, но скорость показывается очень странно, то она у всех клиентов по нулям то гигабайты/террабайты в сек
![IMG_3805](https://github.com/user-attachments/assets/e051c9ce-e9a9-4079-9c0c-58d294ad9bf8)

**Comment by TheMurmabis** [comment]
Здравствуйте. Да, спасибо. Я гляну в чем может быть проблема.

**Comment by TheMurmabis** [comment]
Правки внесены.
