### ISSUE TITLE
Странная сортировка

### ISSUE THREAD

**Issue by Plyha** [TheMurmabis/StatusOpenVPN#16]
Сортирую по размеру

![image](https://github.com/user-attachments/assets/ad2ac86c-5019-4ac9-bce5-335a575b7099)

**Comment by TheMurmabis** [comment]
Обновлено до последней версии?

**Comment by TheMurmabis** [comment]
Сегодня вносил правки в сортировку, после этого ошибка?

**Comment by Plyha** [comment]
Нет, я обновлял позавчера

**Comment by TheMurmabis** [comment]
Тогда надо обновиться)

**Comment by Plyha** [comment]
да, обновился, теперь нормально
![image](https://github.com/user-attachments/assets/348979db-59a0-4493-b78e-efd20561704e)
