### ISSUE TITLE
Смещение центрального блока вправо

### ISSUE THREAD

**Issue by Armaelius** [TheMurmabis/StatusOpenVPN#4]
Доброе. Может поможет в поиске проблемы..
Chrome на Windows и Manjaro - одинаковая картина
Прикладываю скриншоты: 
1  - смещения блока
2  - какой параметр нашел
3 - поменял margin-left на margin, чтобы блок выровнялся
![e2rf3](https://github.com/user-attachments/assets/dda81b66-d588-4913-b35f-2704d113b9ae)
![ice_screenshot_20241031-172509](https://github.com/user-attachments/assets/5c5cf396-c78d-4918-a620-ccf59b8a63c6)
![ice_screenshot_20241031-172453](https://github.com/user-attachments/assets/acd411c6-629a-4df5-92db-203224988d58)

**Comment by TheMurmabis** [comment]
Доброе. да шаблон будет правится в ближайшее время)

**Comment by TheMurmabis** [comment]
Правки внесены.
