### ISSUE TITLE
Запрос функции: отображение IP клиентов

### ISSUE THREAD

**Issue by Armaelius** [TheMurmabis/StatusOpenVPN#9]
Здравствуйте, можно сделать выбор (галочку например), отображать\скрывать IP клиентов? Иногда нужно посмотреть не залазия в терминал... Как я понял, можно тупо экранировать в  main.py:
```
def mask_ip(ip_address):
    ip = ip_address.split(":")[0]
    parts = ip.split(".")
    if len(parts) == 4:
        # Добавляем ведущие нули, чтобы каждая часть занимала 3 символа
        parts = [f"{int(part):03}" for part in parts]

        #return f"{parts[0]}.***.***.{parts[3]}" #Вот эту вот строку
    return ip_address

```
Спасибо :)

**Comment by TheMurmabis** [comment]
Здравствуйте. Постараюсь в ближайшем обновлении добавить эту галочку)

**Comment by TheMurmabis** [comment]
Отображение IP-адресов добавлено.

**Comment by Armaelius** [comment]
Большое спасибо!
